# version: 2.1
# orbs:
#   # "cypress-io/cypress@1" installs the latest published
#   # version "1.x.y" of the orb. We recommend you then use
#   # the strict explicit version "cypress-io/cypress@1.x.y"
#   # to lock the version and prevent unexpected CI changes
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       # - cypress/run # "run" job comes from "cypress" orb
#       steps:
#         -run:     
#             name : testing
#             spec: 'npx cypress run --spec cypress/integration/Campaign/Favourite.js'
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs: 
      - cypress/run:
          spec: cypress/integration/Application/*.js
      # - cypress/run:
      #     spec: cypress/integration/IntermediaryInvestor/Intermediary.js